In [1]:
from sklearn import preprocessing
import numpy as np
X = np.array(np.random.randn(4,5))

In [2]:
X

array([[ 1.31048727, -0.63751066, -0.46837262,  0.77693477,  0.67239798],
       [-0.04387473,  0.52615592, -1.21615703, -0.81037365,  2.35862488],
       [-1.82811866,  0.23286428,  0.31963817, -0.08590386,  1.0909363 ],
       [ 1.58915007,  0.19401608, -0.13632761, -0.08773245, -0.84271196]])

In [3]:
X = preprocessing.scale(X)
X

array([[ 0.77868216, -1.65417328, -0.16610323,  1.47379556, -0.12895402],
       [-0.22230614,  1.03277185, -1.50071461, -1.34912955,  1.34611617],
       [-1.5410136 ,  0.35555162,  1.24030234, -0.06070699,  0.2371731 ],
       [ 0.98463758,  0.26584982,  0.4265155 , -0.06395902, -1.45433526]])

In [6]:
X.mean(axis=0)
X.std(axis=0)

array([1., 1., 1., 1., 1.])

In [10]:
X = np.array(np.random.randn(4,5))
scaler=preprocessing.StandardScaler()
scaler.fit(X)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [11]:
scaler.mean_

array([0.43420437, 0.02643106, 0.23938894, 0.27061898, 0.45097841])

In [12]:
scaler.scale_

array([0.49138286, 0.78694018, 0.34389158, 0.68212055, 0.63927428])

In [14]:
X = scaler.transform(X)

**主要用到了fit() trandform()  transform_fit() 三个方法**

In [15]:
X = np.random.randint(0,5,(4,5))

In [16]:
X

array([[0, 1, 2, 2, 1],
       [2, 0, 0, 2, 3],
       [2, 3, 1, 4, 1],
       [1, 2, 2, 2, 1]])

In [19]:
min_max_scaler = preprocessing.MinMaxScaler()
X_tran = min_max_scaler.fit_transform(X)

D:\Software\Anaconda\envs\python3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [24]:
X_test = np.array([[-3., -1.,  4.,5,6]])

In [25]:
X_test_minmax = min_max_scaler.transform(X_test)

In [26]:
min_max_scaler.min_

array([ 0. ,  0. ,  0. , -1. , -0.5])

In [ ]:
min